### PR TITLE
ci(workflows/ci): setup node before enabling corepack

### PR DESCRIPTION
**Pull request by JounQin**

### CODE REVIEW

**Comment by JounQin** [comment]
@ljharb Did you change my permission on this repository? I can no longer merge this PR with privilege.

**Comment by ljharb** [comment]
You have “maintain” permission; it seems like you should be able to merge it. Is the socket failure blocking it?

**Comment by JounQin** [comment]
OK, I'm not so familiar with `merge queue` feature, it seems not blocking now.

**Comment by JounQin** [comment]
@ljharb I'm not sure why npm permission is not recognized in CI, and I don't have permission to check the secrets used in CI any longer.

https://github.com/import-js/eslint-import-resolver-typescript/actions/runs/9928981640/job/27425949199

**Comment by ljharb** [comment]
the NPM_TOKEN secret exists, but its value can’t be seen, only changed. I’m not familiar with changesets but i wouldn’t expect anything to have changed unless your own npm token changed. Hit me up privately and we can get it sorted.

**Pull request merged**
