### PR TITLE
fix: ignore bun built-in modules

### PR DESCRIPTION
**Pull request by SunsetTechuila**
supersedes #266

[npm link](https://www.npmjs.com/package/is-bun-module)

### CODE REVIEW

**Comment by SunsetTechuila** [comment]
btw this
https://github.com/import-js/eslint-import-resolver-typescript/blob/ca11f1c538714252ff058a8e1c680796ee5775d0/src/index.ts#L163
can be changed to
```ts
builtinModules.includes(source.replace(/^node:/, ''))
```
see https://nodejs.org/api/module.html#modulebuiltinmodules

**Comment by SunsetTechuila** [comment]
@JounQin hello, would appreciate a review from you

**Comment by SunsetTechuila** [comment]
@SukkaW would you mind reviewing my pr as well please? it doesn't look like JounQin will have time for that any time soon

**Comment by SukkaW** [comment]
> @SukkaW would you mind reviewing my pr as well please? it doesn't look like JounQin will have time for that any time soon

Currently, I don't have access to the `eslint-import-resolver-typescript` package yet, thus I can't get my hand on maintaining this. The PR LGTM though.

**Comment by JounQin** [comment]
@SunsetTechuila Sorry for the delay, could be rebase this PR?

@ljharb Is that possible to add @SukkaW as collaborator of this repository also?

**Comment by ljharb** [comment]
done

**Comment by SunsetTechuila** [comment]
rebased

**Review by JounQin — APPROVED** [review]

**Pull request merged**
